### ISSUE TITLE
Can pair only one time after erase_flash

### ISSUE THREAD

**Issue by muek14** [aed3/PS4-esp32#47]
I use this controller https://www.amazon.de/gp/product/B09ZKTNS5F/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 have no problems to change MAC with SixPairTools and can also pair to my ESP32 but it's only possible one time, after I have done the command **_esptool.py --chip esp32 erase_flash_** before flashing the program. After a reset of my ESP32 I try to pair again, the light on the controller ist flashing 2-4 times, but no more pairing ist possible. 

After erase_flash and flashig the program again, pairing is possible again one time.

Have anyone an idea what is wrong in this library?

best regards from vienna/austria Klaus

**Comment by beniroquai** [comment]
same here, did you find a solution for this? somehow related. #40?

**Comment by muek14** [comment]
> same here, did you find a solution for this? somehow related. #40?

oh yes, thanks for this hint, with this workaround I can life, I habe added the relevant code lines to remove the paired devices in my init function, and now it works fine

best regards from vienna/austria Klaus
